[package]
name = "cargo-ndk"
version = "0.4.1"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
repository = "https://github.com/bbqsrc/cargo-ndk"
documentation = "https://docs.rs/cargo-ndk"
homepage = "https://github.com/bbqsrc/cargo-ndk"
license = "MIT/Apache-2.0"
description = "Makes building Rust libraries for Android easy"
keywords = ["ndk", "cargo", "android", "build"]
categories = ["command-line-utilities", "config", "os", "development-tools::cargo-plugins", "development-tools::build-utils"]
edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
clap = "2.33.0"
log = "0.4.8"
env_logger = "0.7.1"